import { createSlice } from '@reduxjs/toolkit';

// Initial state fetching userInfo from localStorage if available
const initialState = {
	userInfo: localStorage.getItem('userInfo')
		? JSON.parse(localStorage.getItem('userInfo'))
		: null,
};

// Create authSlice using createSlice
const authSlice = createSlice({
	name: 'auth', // Slice name
	initialState, // Initial state
	reducers: {
		// Reducer to set user credentials
		setCredentials: (state, action) => {
			state.userInfo = action.payload; // Update userInfo in state
			localStorage.setItem('userInfo', JSON.stringify(action.payload)); // Update userInfo in localStorage
		},
		// Reducer to logout user
		logout: (state) => {
			state.userInfo = null; // Clear userInfo in state
			localStorage.clear(); // Clear all localStorage data
		},
	},
});

// Export actions generated by createSlice
export const { setCredentials, logout } = authSlice.actions;

// Export reducer generated by createSlice
export default authSlice.reducer;
